/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Obiwan(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "/models/ObiwanAnimated.glb"
  );
  const { actions } = useAnimations(animations, group);

  console.log("Obiwan actions", actions);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <skinnedMesh
            name="Object_2"
            geometry={nodes.Object_2.geometry}
            material={materials.Obiwan}
            skeleton={nodes.Object_2.skeleton}
          />
          <primitive object={nodes.mixamorigHips} />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/ObiwanAnimated.glb");
